version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kutubxona_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Farishtam@localhost
      POSTGRES_DB: kutubxona_db
    ports:
      - "5432:5432"
    volumes:
      - bdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kutubxona_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:Farishtam%40localhost@db:5432/kutubxona_db
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    volumes:
      - app_uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kutubxona_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

  db-backup:
    image: postgres:15-alpine
    container_name: kutubxona_db_backup
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backups:/backups
      - ./backup.sh:/backup.sh:ro
    environment:
      PGUSER: postgres
      PGPASSWORD: Farishtam@localhost
      PGHOST: db
      PGDB: kutubxona_db
    entrypoint: >
      sh -c " chmod +x /backup.sh && echo '0 5 * * 0 /backup.sh' > /etc/crontabs/root && crond -f -l 2 "
    restart: unless-stopped

volumes:
  bdata:
  app_uploads:
